Vagrant.configure("2") do |config|

  config.vm.box = "kalilinux/rolling" #Box Vagrant a utiliser : image kalilinux
  config.vm.hostname = "kali-linux"

  config.vm.network "forwarded_port", guest: 80, host: 8080 #Redirection du port 80 de la VM vers le port 8080 de l'hôte pour accéder aux services web de la VM depuis l'hôte

  config.vm.provider "virtualbox" do |v| #config de la VM : 4Go de RAM et 4 coeurs CPU
    v.memory = "4096"
    v.cpus = 4
    v.name = "pentest-server-vm"
    v.gui = false # Désactiver l'interface graphique
  end

  # Provisioning : installe les outils de pentesting et Docker qui seront utilisés pour le déploiement des conteneurs

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml" # Fichier playbook Ansible à exécuter
    ansible.inventory_path = "inventory.ini" # Fichier d'inventaire Ansible à utiliser
    ansible.limit = "all" # Limite l'exécution du playbook à tous les hôtes définis dans l'inventaire
  end

end